# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ggml_ir

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GgmlGraph(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GgmlGraph()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGgmlGraph(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GgmlGraph
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GgmlGraph
    def Tensors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from ggml_ir.Tensor import Tensor
            obj = Tensor()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GgmlGraph
    def TensorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GgmlGraph
    def TensorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # GgmlGraph
    def NThreads(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

def GgmlGraphStart(builder):
    builder.StartObject(2)

def Start(builder):
    GgmlGraphStart(builder)

def GgmlGraphAddTensors(builder, tensors):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(tensors), 0)

def AddTensors(builder, tensors):
    GgmlGraphAddTensors(builder, tensors)

def GgmlGraphStartTensorsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartTensorsVector(builder, numElems):
    return GgmlGraphStartTensorsVector(builder, numElems)

def GgmlGraphAddNThreads(builder, nThreads):
    builder.PrependInt32Slot(1, nThreads, 1)

def AddNThreads(builder, nThreads):
    GgmlGraphAddNThreads(builder, nThreads)

def GgmlGraphEnd(builder):
    return builder.EndObject()

def End(builder):
    return GgmlGraphEnd(builder)
