# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ggml_ir

class TensorType(object):
    F32 = 0
    F16 = 1
    I64 = 2
    I32 = 3
    BOOL = 4
    BF16 = 5
    Q8_0 = 6
    Q6_K = 7
    Q4_0 = 8
